#!/usr/bin/env python3
"""
extract_borders.py — reads countries.geojson, outputs include/CountryBorders.h
with simplified polygon outlines for 20 key countries.
"""
import json, sys, os

COUNTRIES = [
    ("USA", "United States"),
    ("GBR", "United Kingdom"),
    ("IND", "India"),
    ("BRA", "Brazil"),
    ("NGA", "Nigeria"),
    ("CHN", "China"),
    ("RUS", "Russia"),
    ("DEU", "Germany"),
    ("FRA", "France"),
    ("MEX", "Mexico"),
    ("PAK", "Pakistan"),
    ("IDN", "Indonesia"),
    ("EGY", "Egypt"),
    ("ZAF", "South Africa"),
    ("ARG", "Argentina"),
    ("JPN", "Japan"),
    ("AUS", "Australia"),
    ("TUR", "Turkey"),
    ("KEN", "Kenya"),
    ("PHL", "Philippines"),
]

geojson_path = os.path.join(os.path.dirname(__file__), "../assets/map/countries.geojson")
out_path     = os.path.join(os.path.dirname(__file__), "../include/CountryBorders.h")

with open(geojson_path) as f:
    gj = json.load(f)

# Build lookup: ADM0_A3 → feature
lookup = {}
for feat in gj["features"]:
    props = feat.get("properties", {})
    code = props.get("ADM0_A3") or props.get("ISO_A3") or props.get("SOV_A3", "")
    if code:
        lookup[code] = feat

def largest_ring(geom):
    """Return the single ring (list of [lon,lat]) with the most points."""
    t = geom["type"]
    if t == "Polygon":
        rings = geom["coordinates"]
    elif t == "MultiPolygon":
        rings = []
        for poly in geom["coordinates"]:
            rings.extend(poly)
    else:
        return []
    if not rings:
        return []
    return max(rings, key=len)

def simplify(ring, max_pts=120):
    """Keep every nth point so we don't exceed max_pts."""
    if len(ring) <= max_pts:
        return ring
    step = len(ring) / max_pts
    return [ring[int(i * step)] for i in range(max_pts)]

lines = []
lines.append("// CountryBorders.h — auto-generated by scripts/extract_borders.py")
lines.append("// Do not edit by hand.")
lines.append("#pragma once")
lines.append("#include <vector>")
lines.append("#include <utility>")
lines.append("#include <string>")
lines.append("")
lines.append("struct CountryDef {")
lines.append("    const char* iso3;")
lines.append("    const char* display_name;")
lines.append("    float lon_min, lon_max, lat_min, lat_max;")
lines.append("    std::vector<std::pair<float,float>> polygon;")
lines.append("};")
lines.append("")
lines.append("inline std::vector<CountryDef> getCountryDefs() {")
lines.append("    return {")

found = []
missing = []

for iso3, name in COUNTRIES:
    feat = lookup.get(iso3)
    if not feat:
        missing.append(iso3)
        # Provide a minimal placeholder
        lines.append(f'        {{"{iso3}", "{name}", -10.f, 10.f, -10.f, 10.f, {{}}}},')
        continue

    geom = feat["geometry"]
    ring = largest_ring(geom)
    ring = simplify(ring, 120)

    lons = [p[0] for p in ring]
    lats = [p[1] for p in ring]

    lon_min, lon_max = min(lons), max(lons)
    lat_min, lat_max = min(lats), max(lats)

    pts = ", ".join(f"{{{p[0]:.4f}f,{p[1]:.4f}f}}" for p in ring)
    lines.append(f'        {{"{iso3}", "{name}", {lon_min:.4f}f, {lon_max:.4f}f, {lat_min:.4f}f, {lat_max:.4f}f,')
    lines.append(f'            {{{pts}}}}},')
    found.append(iso3)

lines.append("    };")
lines.append("}")

with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Written {out_path}")
print(f"  Found:   {found}")
if missing:
    print(f"  Missing: {missing}")
